### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by kyakusahmed**
pull request 1

### CODE REVIEW

**Comment by ekumamait** [comment]
Nice work

**Comment by joelethan** [comment]
This is great. However i have been told we are supposed the comments in present tense Eg. Add html file

**Comment by mariamiah** [comment]
Great work

**Comment by Phionamary** [comment]
This is great work Ahmed, however, your commit messages should be in present tense for example: "Add CSS File". Also, have you integrated with Pivotal tracker yet? I do not see any IDs in your commit messages. Please work on those.

**Pull request merged**
